### ISSUE TITLE
Pin It button & Follow Button shortcode

### ISSUE THREAD

**Issue by EugenioPetulla** [deshack/pinit#11]
Is it good for you if I code this two buttons into shortcode?

Would be a good idea maybe to make the follow button as a widget as well?

**Comment by deshack** [comment]
Currently the widget is based on shortcodes (renders badges through `do_shortcode()`. So it's quite simple to create a widget starting from the relative shortcode.
Go ahead, drink coffee and code! \m/

**Comment by EugenioPetulla** [comment]
Are you sure? I can't find any do_shortcode reference into the code.

Actually seems to be a good solid widget based on the html structure of pinterest badge, using html data-pin-do meta to retrieve the kind of badge to render.

If you look at the structure of the "follow" badge you will notice that you have to specificate also the content of the button so you have to put an additional input field for the widget in order to accomplish this.

https://developers.pinterest.com/tools/widget-builder/?type=follow

**Comment by deshack** [comment]
Well, maybe I don't remember well.. Forgive me!

**Comment by EugenioPetulla** [comment]
Don't worry. It's my issue now. :D
