### ISSUE TITLE
Clash of class in admin.js

### ISSUE THREAD

**Issue by EugenioPetulla** [deshack/pinit#14]
This will cause a big usability bug.

To reproduce the issue drag more than one widget in the same widget area and select the first one as Pin. You will be not able to set size value of the second one because your js is hiding the input boxes.
![schermata da 2016-02-12 14-00-36](https://cloud.githubusercontent.com/assets/3589467/13007575/970e6b4a-d191-11e5-8742-b2749c91d2fe.png)
![schermata da 2016-02-12 14-00-48](https://cloud.githubusercontent.com/assets/3589467/13007574/970e23b0-d191-11e5-931a-af89e29de54e.png)

**Comment by deshack** [comment]
I'll work on this ASAP.

**Comment by EugenioPetulla** [comment]
Thanks a lot!
Milestone in 2.0.1 or we delay the 2.0.0 release in order to put the fix in?

**Comment by deshack** [comment]
@EugenioPetulla 2.0.1 ;)

**Comment by EugenioPetulla** [comment]
it works like a charm! :)

@deshack :+1:
