### ISSUE TITLE
Add contributors instructions for non-technicians

### ISSUE THREAD

**Issue by deshack** [deshack/pinit#16]
At least in the demo website, we need some info on how to contribute with things like translations.

See #5

**Comment by EugenioPetulla** [comment]
I take care of this as soon as possible.

**Comment by EugenioPetulla** [comment]
http://codeat.co/pinit/contribute/

Do you want add anything? @deshack

**Comment by deshack** [comment]
The text is good, but I would highlight some words to help focus on the different ways to contribute to the project (with bold text):



> If you are a **developer** and want to help us improving this little piece of code please fork it on GitHub, open a issue or a direct pull request if you think it’s a good choice.
> 
> We are open to every kind of contribution so if you are a **translator** and want to give us a feeback or want include a new language for this project you have to know that we use standard .po and .pot languages file formats.
> 
> Download the .pot directly from GitHub or push the button on this page and start edit it with Poedit.
> Open a GitHub issue or leave us a message using the form below and we will reply as soon as possible.

**Comment by EugenioPetulla** [comment]
Did it! :)

http://codeat.co/pinit/contribute/

**Comment by deshack** [comment]
Well done @EugenioPetulla
