### ISSUE TITLE
Settings help improvements

### ISSUE THREAD

**Issue by deshack** [deshack/pinit#21]
s/activate/activated:

> This feature will be **activate** on EVERY image of your website.

s/post/posts and s/could/can:

> Activate Pinit buttons in sigle **post** only (This **could** be combined with pages)

s/could/can:

> Activate Pinit buttons in sigle pages only (This **could** be combined with posts)

Also, I would remove the _only_ from the last two. _only_ implies that you cannot have both settings active at the same time, but what's written between brackets says the opposite. It's kind of confusing to me.

**Comment by deshack** [comment]
The help for _button color_ and _language_ settings can be improved a little bit:

> Useless if round buttons are active

Might be:

> Useless if round button setting is active

**Comment by EugenioPetulla** [comment]
Ok for post/can and button setting flag.

What do you think about this for *single post/pages options* ?

**Label**
> Activate Pinit buttons in single post

**Description**
> This can be combined with pages and prevent activation in other post types, archives and pages.

**Comment by deshack** [comment]
@EugenioPetulla tell me more about the way single posts/pages options work. If you leave them unchecked, the button will be activated for every post type, while checking them will enable it only in the post types specified?

**Comment by EugenioPetulla** [comment]
Correct! If you just activate the functionality is sitewide but if you check the options it will be active only in single post or/and pages.

I'm working on a special CMB2 field that automatically checks for all CPTs activated in the website so in a future release page/post options will be more granular and tunable.

:)

**Comment by deshack** [comment]
Ok, that is what I was thinking about.
