### ISSUE TITLE
Add more granularity to pinit button option

### ISSUE THREAD

**Issue by EugenioPetulla** [deshack/pinit#26]
- [x] Single Post (new using method or function to check both parameters)
- [x] Single Pages (new using method or function to check both parameters)
- [x] Front Page
- [x] Tags Archive
- [x] Categories Archive
- [x] Author Archive
- [x] Single Product (WooCommerce)
- [x] Products Archives (WooCommerce)
- [x] Shop Page (WooCommerce)

Add an option for pinit button into archives, frontpage, blogpage, category pages and tag pages.

Maybe the WooCommerce option for products pages could be enabled only if woo is active.
##

**Comment by EugenioPetulla** [comment]
@deshack I'm done and I think this feature is ready for 2.1.0 release, it's a waste of time releasing it later, it's finished and tested.

This feature also improve the settings page looks'n feeling, partially patching some aspects discussed on #28 :)

![schermata da 2016-03-01 05-36-54](https://cloud.githubusercontent.com/assets/3589467/13417849/c752c6e8-df6f-11e5-898e-c411104cd0cd.png)

**Comment by deshack** [comment]
This has been released with 2.1.0 if I'm right. Closing it.

**Comment by EugenioPetulla** [comment]
We have to documenting this Woocommerce feature in the readme maybe!
