### ISSUE TITLE
Button color option doesn't work

### ISSUE THREAD

**Issue by deshack** [deshack/pinit#32]
### Steps to reproduce
Go to the Pinit settings page (`/wp-admin/admin.php?page=pinit`), check the _Insert Pinit Button on hover_, and change the _Button Color_ setting to either _Grey_ or _White_. Leave the _Round Button_ setting unchecked.
Go to the frontend, reload the page, and hover over an image.

### Expected behaviour
The Pinit button that appears on hover is either gray or white, according to the selection.

### What happens instead
The button is still red.

### Considerations
Looking at the [Pinterest widget builder](https://developers.pinterest.com/tools/widget-builder/?type=pinit) there is no evidence of this option. Maybe they removed it recently. We should remove it from our plugin too.

**Comment by EugenioPetulla** [comment]
You are right, they just rebranded buttons and removed this feature. We have to do the same!

I will push the new code in this days, keep an eye so you can push a new release on the wordpress repo! :)

**Comment by deshack** [comment]
Ok @EugenioPetulla, can I assign this to you, since you're already working on new code?

Also, should we schedule it for v2.2.0 instead of v2.1.1?

**Comment by EugenioPetulla** [comment]
Yes @deshack assign it to me but we can plan a minor for this, I think we can consider it a fix not an enhancement. :)
