### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by deshack** [deshack/pinit#5]

**Comment by EugenioPetulla** [comment]
Please give me some suggestions about this task. :)

**Comment by deshack** [comment]
There should be some translations missing or old @EugenioPetulla

**Comment by EugenioPetulla** [comment]
Nothing on my side, I'll check ITA and ENG files but I don't know how to do it with other languages. Transifex? Other service? Point me to where you asked for translations please. :)

**Comment by deshack** [comment]
Currently I don't use any particular service for translations, so we just need to choose one. Did you use Transifex @EugenioPetulla? How is it?

**Comment by EugenioPetulla** [comment]
Free for open source projects but is useless to me for this little plugin. We don't need very complicated translations. Maybe we need just a check on G Translate.

**Comment by deshack** [comment]
It's better having old translations than use G Translate, IMO. We can also tell people to use Poedit and open a PR here on GitHub to submit translations. Not that easy for non-technicians, but better than G Translate I think!

**Comment by EugenioPetulla** [comment]
Ok for the old translations, redirectiong peolple here is good too and I'll put a contact/contribute form into the website soon for non-technicians. :)

**Comment by deshack** [comment]
ok, follows in #16 then.
