### ISSUE TITLE
Test shortcodes

### ISSUE THREAD

**Issue by deshack** [deshack/pinit#6]

**Comment by EugenioPetulla** [comment]
???

Please, leave a description for this task! :confused:

**Comment by deshack** [comment]
I think i's a matter of adding some automated tests to ensure everything is OK through different WordPress releases and while adding new features.
I mean, we could even implement something with PHPUnit and Travis CI if you please.

**Comment by EugenioPetulla** [comment]
I'll accomplish it by creating a Demo website showing all shortcode, auto-update enabled, so for every release there will be a sort of automated test. Is it good enough to you or do you want suggest something more "traditional" ? :)

**Comment by EugenioPetulla** [comment]
http://codeat.co/pinit/simple-shortcodes/

Demo page created. :)

**Comment by EugenioPetulla** [comment]
Page populated and shortcode tested. :+1:

**Comment by deshack** [comment]
It's good enough. We could implement some unit tests to ensure the logic of the plugin is always ok, but it's not urgent.
